### ISSUE TITLE
feat: Implement custom backends

### ISSUE THREAD

**Issue by logan-bobo** [logan-bobo/prism-lb#5]
currently the backends are static and instantiated in `main` then passed into the server. This issue is to implement functionality that will allow users to define a custom `backends.yaml` file with the following schema

```yaml
---
bindInterface: 0.0.0.0
bindPort: 80
backends:
  - host: backendA
    port: 8080
  - host: backendB
    port: 8080
healthCheck:
  interval: 60
  failureThreshold: 3
```
