### ISSUE TITLE
feat: Implement health check

### ISSUE THREAD

**Issue by logan-bobo** [logan-bobo/prism-lb#6]
Unealthy nodes should be not be avaluated in request forwarding, this issue is to implement a worker thread that will periodically check the health of a backend. If the backend has failed it health check at the specified for the ammount of `failureThreshold` it will be removed from the routable pool.

```yaml
---
healthCheck:
  interval: 60
  failureThreshold: 3
```
